### ISSUE TITLE
Not currently working

### ISSUE THREAD

**Issue by HeliumFreak** [Tusko/vimeo-private-downloader#22]
No longer works with current private videos unfortunatly. 

`undefined:1
<HTML><HEAD>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\Helium\Downloads\vimeo-private-downloader-master\vimeo-private-downloader-master\vimeomaster.js:135:41)
←[90m    at IncomingMessage.emit (events.js:327:22)←[39m
←[90m    at endReadableNT (internal/streams/readable.js:1327:12)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)←[39m
`

**Comment by electroheadfx** [comment]
me too but I have no error, the m4v video can't read, it combine nothing

**Comment by NaanProphet** [comment]
Same here, seems to be an issue with the `moov` atom.

For what it's worth I tried https://github.com/eMBee/vimeo-download and it downloads the file correctly. Perhaps someone can research how it is working there and suggest a fix to this repo.

**Comment by hkvincent** [comment]
> me too but I have no error, the m4v video can't read, it combine nothing

yes, me too, the video can not read but without any download error. 
someone can help to fix it? thank you very much.

**Comment by pirocorp** [comment]
> For what it's worth I tried https://github.com/eMBee/vimeo-download and it downloads the file correctly.

Thanx, the tool you specified is working correctly.

**Comment by Tusko** [comment]
Guys, everything is working fine
Please check the video how it works
https://share.getcloudapp.com/NQuJZ6ND

The example link of `master.json`
https://60vod-adaptive.akamaized.net/exp=1585642273~acl=%2F290272859%2F%2A~hmac=83af394043c1f9e24e0b1ffdd22e771c0ef2106a6a6ce4cf5e6a288dba76ceef/290272859/sep/video/1099558424,1099558420,1099557256,1099557251/master.json?base64_init=1

Have you seen that links have an expiration date/time?
`exp=1585642273`

Expired links brokes the script.
I've fixed it in the latest commit

**Comment by NaanProphet** [comment]
The latest commit does not solve my issue, as it is a currently working link. Using the same link with https://github.com/eMBee/vimeo-download works correctly.

**Comment by hkvincent** [comment]
> The latest commit does not solve my issue, as it is a currently working link. Using the same link with https://github.com/eMBee/vimeo-download works correctly.

hi can you tell me which python version you are using. since I can not pip the requirement file. thanks

**Comment by pirocorp** [comment]
> 
> hi can you tell me which python version you are using. since I can not pip the requirement file. thanks

For [eMBee/vimeo-download](https://github.com/eMBee/vimeo-download) change in vimeo-download.py 

```python
import urlparse
```
 with 

```python
try:
    import urlparse
except ImportError:
    import urllib.parse as urlparse
```
